git:
  depth: 1
branches:
  only:
    - wip_mlt
addons:
  chrome: stable
env:
  global:
    - secure: "d0qFbD7GhsyaLgsulFD5tMMFHyuqAn8LrjC5DVOK6OvHx7T0Z9cjetzxxm+h+Gz5eAUfclS8d5P8iJQGRpVgwF+6EBoyLDAvJTCt7+N0FTTqsJwupQynfr3wtnqTbqQIsgAHB9kmz3WPoPztLbragOiFSZLMAkSOj3qKtpVwpeEmaXZe2r+dafrwWE7uFt+hnnLCxmSznGE+c8habCi+PTwtCmbUDkf4l68Nmvn7+iE11b9RVVRNGLNdfxQo85LL57dN/6midA3pL8djBkokPTjHrchA4mg1z9vR0KjW6iA6HdkSq/EtFRTVrFyJqHwuO0u8WIIQWlxmutEBLNpoTsgqQFxwUhVl3ymy/xZQWHCHCXf/+N+zitV8OWQrqx+vgb81QbHjsi1wGpMbOWODEaSfsLqQTnTeuhlFMmMWM97+PaPorou54x69QAO2wT5ip8NZBSv0l0p3/NS3ShEw2h6JuRmH3NTUH2dN5mMKkwGm3aJQNWOPYc+SNbW6p6+P75rzLisdHkAlV/hqh6K3dOVlau3/4H11mLI2mMEwIxrm+wbhhKfu/gyo6/YV6VoojF1Alqo14P5b9Vmm8V4+sP6m8DPEyi5AQtqXi+Rw+GKeYHPIeGIUY5vs0PzB4lG3eYKh/1bLWHtaXMXVW3fCKQnpYNGl3id/uzmKkRXSajA="
language: ruby
rvm:
  -  2.4.4
  -  2.5.1
  -  jruby-9.2.0.0
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    - /home/travis/.chromedriver-helper/
before_install:
  - openssl aes-256-cbc -K $encrypted_1be6b4981a28_key -iv $encrypted_1be6b4981a28_iv -in gcs_credentials.json.enc -out gcs_credentials.json -d
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "bundle exec rspec spec"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

